# Generated by Django 3.2.16 on 2022-10-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birthdate',
        ),
    ]
