# Generated by Django 3.2.16 on 2022-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_remove_myuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='verified'),
        ),
    ]
